language: android

sudo: false

env:
  global:
      - ANDROID_BUILD_TOOLS_VERSION=25.0.0
      - ADB_INSTALL_TIMEOUT=10

  #matrix:
  #  - ANDROID_TARGET=android-22  ANDROID_ABI=armeabi-v7a

android:
  components:

    # Use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - tools

    - build-tools-25.0.1
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify the system image to run emulator during tests
    - sys-img-armeabi-v7a-android-25

  licenses:
      - 'android-sdk-preview-license-52d11cd2'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'

jdk:
  - oraclejdk8

os:
  - linux

before_script:
  # Create and start emulator
  #- chmod +x gradlew
  - pip install --user codecov
  #- echo no | android create avd --force -n test -t android-25 --abi armeabi-v7a
  #- emulator -avd test -no-skin -no-audio -no-window &
  #- android-wait-for-emulator
  #- adb shell input keyevent 82 &

script:
  - ./gradlew build test

after_success:
  - bash <(curl -s https://codecov.io/bash)
